### ISSUE TITLE
How to use this file?

### ISSUE THREAD

**Issue by jarygrace** [warrenlp/OpenCV_Rectangle_Detection#1]

**Comment by warrenlp** [comment]
Make sure that you have opencv installed. I recommend using Ubuntu for experimentation.
The easiest way to install opencv in Ubuntu that I have found, but it won't give you the latest:
sudo apt-get install libopencv-dev

Build with this command from this cloned repo:
g++ squares.cpp -o squares `pkg-config --cflags --libs opencv`
There are back-quotes here:  ^                                                ^ that aren't showing up for some reason.
